# Generated by Django 5.2.7 on 2025-10-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_frame_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='slug',
        ),
    ]
