services:
    django:
        image: etinier/nostalgia:latest
        restart: unless-stopped
        volumes:
            - ./:/app
            - static_volume:/app/staticfiles
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    caddy:
        image: caddy:2.10-alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./config/caddy:/etc/caddy
            - /var/www/nostalgia:/usr/share/caddy
            - caddy_data:/data
            - caddy_config:/config

volumes:
    postgres_data: {}
    static_volume: {}
    caddy_data: {}
    caddy_config: {}
